{{
    set monitorMajorMinor to join(slice(split(PRODUCT_VERSION, "."), 0, 2), ".") ^
    set buildVersion to VARIABLES[cat("monitor|", monitorMajorMinor, "|build-version")] ^
    set productVersion to VARIABLES[cat("monitor|", monitorMajorMinor, "|product-version")] ^
    set monitorBaseUrl to cat(VARIABLES[cat("monitor|", monitorMajorMinor, "|base-url|", VARIABLES["branch"])], "/diagnostics/monitor/$dotnet_monitor_build/") ^
    set files to [
        [
            "filename": "dotnet-monitor-base.tar.gz",
            "url": cat(monitorBaseUrl, "dotnet-monitor-base-$dotnet_monitor_version-linux-", ARCH_SHORT, ".tar.gz"),
            "sha": VARIABLES[join(["monitor-base", monitorMajorMinor, "linux", ARCH_SHORT, "sha"], "|")],
            "sha-var-name": "dotnet_monitor_base_sha512"
        ]
    ]
}}RUN dotnet_monitor_version={{productVersion}} \
    dotnet_monitor_build={{buildVersion}} \
    && {{InsertTemplate("../Dockerfile.linux.download-and-install",
        [
            "files": files,
            "install-dir": "/app",
            "create-install-dir": "true"
        ], "    ")}}
