{{
    set monitorMajorMinor to join(slice(split(PRODUCT_VERSION, "."), 0, 2), ".") ^
    set buildVersion to VARIABLES[cat("monitor|", monitorMajorMinor, "|build-version")] ^
    set productVersion to VARIABLES[cat("monitor|", monitorMajorMinor, "|product-version")] ^
    set isAlpine to find(OS_VERSION, "alpine") >= 0 ^
    set varPlatform to when(isAlpine, "linux-musl", "linux") ^
    set monitorBaseUrl to cat(VARIABLES[cat("monitor|", monitorMajorMinor, "|base-url|", VARIABLES["branch"])], "/diagnostics/monitor/$dotnet_monitor_build/") ^
    set files to [
        [
            "filename": "dotnet-monitor.tar.gz",
            "url": cat(monitorBaseUrl, "dotnet-monitor-$dotnet_monitor_version-", varPlatform, "-", ARCH_SHORT, ".tar.gz"),
            "sha": VARIABLES[join(["monitor", monitorMajorMinor, varPlatform, ARCH_SHORT, "sha"], "|")],
            "sha-var-name": "dotnet_monitor_sha512"
        ]
    ]
}}RUN dotnet_monitor_version={{productVersion}} \
    dotnet_monitor_build={{buildVersion}} \
    && {{InsertTemplate("../Dockerfile.linux.download-and-install",
        [
            "files": files,
            "install-dir": "/app",
            "create-install-dir": "true"
        ], "    ")}}
